[package]
name = "rust"
version = "0.1.0"
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
fs_extra = "1.1.0"
copy_dir = "0.1.2"
regex = "1.1.0"
